-- =============================================================================
-- Constraint Rename Script — Phase 6: 08-learning
-- =============================================================================

-- 08.01 learning_materials
ALTER TABLE public.learning_materials RENAME CONSTRAINT learning_materials_pkey TO pk_learning_materials;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_tenant TO fk_learning_materials_institutes;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_course TO fk_learning_materials_courses;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_subject TO fk_learning_materials_subjects;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_chapter TO fk_learning_materials_chapters;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_topic TO fk_learning_materials_topics;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_batch TO fk_learning_materials_batches;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_published_by TO fk_learning_materials_users_published_by;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_created_by TO fk_learning_materials_users_created_by;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_updated_by TO fk_learning_materials_users_updated_by;
ALTER TABLE public.learning_materials RENAME CONSTRAINT fk_learning_materials_deleted_by TO fk_learning_materials_users_deleted_by;
ALTER TABLE public.learning_materials RENAME CONSTRAINT uq_learning_material_code TO uq_learning_materials_material_code;
ALTER TABLE public.learning_materials RENAME CONSTRAINT chk_material_code TO chk_learning_materials_material_code;
ALTER TABLE public.learning_materials RENAME CONSTRAINT chk_material_title TO chk_learning_materials_title;
ALTER TABLE public.learning_materials RENAME CONSTRAINT chk_material_duration TO chk_learning_materials_estimated_duration;
ALTER TABLE public.learning_materials RENAME CONSTRAINT chk_material_reading_time TO chk_learning_materials_reading_time;
ALTER TABLE public.learning_materials RENAME CONSTRAINT chk_material_version TO chk_learning_materials_version;
ALTER INDEX IF EXISTS idx_lm_tenant_course RENAME TO idx_learning_materials_tenant_course;
ALTER INDEX IF EXISTS idx_lm_tenant_subject RENAME TO idx_learning_materials_tenant_subject;
ALTER INDEX IF EXISTS idx_lm_tenant_chapter RENAME TO idx_learning_materials_tenant_chapter;
ALTER INDEX IF EXISTS idx_lm_tenant_topic RENAME TO idx_learning_materials_tenant_topic;
ALTER INDEX IF EXISTS idx_lm_tenant_batch RENAME TO idx_learning_materials_tenant_batch;
ALTER INDEX IF EXISTS idx_lm_tenant_type RENAME TO idx_learning_materials_tenant_type;
ALTER INDEX IF EXISTS idx_lm_tenant_status RENAME TO idx_learning_materials_tenant_status;
ALTER INDEX IF EXISTS idx_lm_tenant_published RENAME TO idx_learning_materials_tenant_published;
ALTER INDEX IF EXISTS idx_lm_search_vector RENAME TO idx_learning_materials_search_vector;
-- uq_learning_materials_tenant_id already compliant

-- 08.02 material_versions
ALTER TABLE public.material_versions RENAME CONSTRAINT material_versions_pkey TO pk_material_versions;
ALTER TABLE public.material_versions RENAME CONSTRAINT fk_material_versions_tenant TO fk_material_versions_institutes;
ALTER TABLE public.material_versions RENAME CONSTRAINT fk_material_versions_material TO fk_material_versions_learning_materials;
ALTER TABLE public.material_versions RENAME CONSTRAINT fk_material_versions_created_by TO fk_material_versions_users_created_by;
ALTER TABLE public.material_versions RENAME CONSTRAINT uq_material_version_number TO uq_material_versions_version;
ALTER TABLE public.material_versions RENAME CONSTRAINT chk_material_version_number TO chk_material_versions_version;
ALTER TABLE public.material_versions RENAME CONSTRAINT chk_material_version_reason TO chk_material_versions_change_reason;
ALTER INDEX IF EXISTS idx_material_versions_material RENAME TO idx_material_versions_material_version;
ALTER INDEX IF EXISTS idx_material_versions_tenant RENAME TO idx_material_versions_tenant_material;
ALTER INDEX IF EXISTS idx_material_versions_created RENAME TO idx_material_versions_tenant_created;
-- uq_material_versions_tenant_id already compliant

-- 08.03 material_attachments
ALTER TABLE public.material_attachments RENAME CONSTRAINT material_attachments_pkey TO pk_material_attachments;
ALTER TABLE public.material_attachments RENAME CONSTRAINT fk_material_attachments_tenant TO fk_material_attachments_institutes;
ALTER TABLE public.material_attachments RENAME CONSTRAINT fk_material_attachments_material TO fk_material_attachments_learning_materials;
ALTER TABLE public.material_attachments RENAME CONSTRAINT fk_material_attachments_created_by TO fk_material_attachments_users_created_by;
ALTER TABLE public.material_attachments RENAME CONSTRAINT fk_material_attachments_updated_by TO fk_material_attachments_users_updated_by;
ALTER TABLE public.material_attachments RENAME CONSTRAINT fk_material_attachments_deleted_by TO fk_material_attachments_users_deleted_by;
ALTER TABLE public.material_attachments RENAME CONSTRAINT chk_attachment_display_order TO chk_material_attachments_display_order;
ALTER TABLE public.material_attachments RENAME CONSTRAINT chk_attachment_duration TO chk_material_attachments_duration;
ALTER TABLE public.material_attachments RENAME CONSTRAINT chk_attachment_file_size TO chk_material_attachments_file_size;
ALTER TABLE public.material_attachments RENAME CONSTRAINT chk_attachment_version TO chk_material_attachments_version;
ALTER INDEX IF EXISTS idx_ma_material RENAME TO idx_material_attachments_material_order;
ALTER INDEX IF EXISTS idx_ma_tenant RENAME TO idx_material_attachments_tenant_material;
ALTER INDEX IF EXISTS idx_ma_storage RENAME TO idx_material_attachments_storage;
ALTER INDEX IF EXISTS idx_ma_type RENAME TO idx_material_attachments_tenant_type;
-- uq_material_attachments_tenant_id already compliant

-- 08.04 learning_paths
ALTER TABLE public.learning_paths RENAME CONSTRAINT learning_paths_pkey TO pk_learning_paths;
ALTER TABLE public.learning_paths RENAME CONSTRAINT fk_learning_paths_tenant TO fk_learning_paths_institutes;
ALTER TABLE public.learning_paths RENAME CONSTRAINT fk_learning_paths_created_by TO fk_learning_paths_users_created_by;
ALTER TABLE public.learning_paths RENAME CONSTRAINT fk_learning_paths_updated_by TO fk_learning_paths_users_updated_by;
ALTER TABLE public.learning_paths RENAME CONSTRAINT fk_learning_paths_deleted_by TO fk_learning_paths_users_deleted_by;
ALTER TABLE public.learning_paths RENAME CONSTRAINT chk_path_title TO chk_learning_paths_title;
ALTER TABLE public.learning_paths RENAME CONSTRAINT chk_path_estimated_days TO chk_learning_paths_estimated_days;
ALTER TABLE public.learning_paths RENAME CONSTRAINT chk_path_version TO chk_learning_paths_version;
ALTER INDEX IF EXISTS idx_lp_tenant_status RENAME TO idx_learning_paths_tenant_status;
ALTER INDEX IF EXISTS idx_lp_tenant_difficulty RENAME TO idx_learning_paths_tenant_difficulty;
-- uq_learning_paths_tenant_id already compliant

-- 08.05 learning_path_materials
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT learning_path_materials_pkey TO pk_learning_path_materials;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT fk_lpm_tenant TO fk_learning_path_materials_institutes;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT fk_lpm_path TO fk_learning_path_materials_learning_paths;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT fk_lpm_material TO fk_learning_path_materials_learning_materials;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT fk_lpm_created_by TO fk_learning_path_materials_users_created_by;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT fk_lpm_updated_by TO fk_learning_path_materials_users_updated_by;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT fk_lpm_deleted_by TO fk_learning_path_materials_users_deleted_by;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT uq_lpm_path_material TO uq_learning_path_materials_path_material;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT uq_lpm_path_order TO uq_learning_path_materials_path_order;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT chk_lpm_display_order TO chk_learning_path_materials_display_order;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT chk_lpm_unlock_days TO chk_learning_path_materials_unlock_days;
ALTER TABLE public.learning_path_materials RENAME CONSTRAINT chk_lpm_version TO chk_learning_path_materials_version;
ALTER INDEX IF EXISTS idx_lpm_path RENAME TO idx_learning_path_materials_path_order;
ALTER INDEX IF EXISTS idx_lpm_material RENAME TO idx_learning_path_materials_material;
ALTER INDEX IF EXISTS idx_lpm_tenant RENAME TO idx_learning_path_materials_tenant_path;
ALTER INDEX IF EXISTS idx_lpm_mandatory RENAME TO idx_learning_path_materials_path_mandatory;
-- uq_lpm_tenant_id already compliant

-- 08.06 student_learning_progress
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT student_learning_progress_pkey TO pk_student_learning_progress;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT fk_slp_tenant TO fk_student_learning_progress_institutes;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT fk_slp_student TO fk_student_learning_progress_student_admissions;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT fk_slp_material TO fk_student_learning_progress_learning_materials;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT fk_slp_created_by TO fk_student_learning_progress_users_created_by;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT fk_slp_updated_by TO fk_student_learning_progress_users_updated_by;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT fk_slp_deleted_by TO fk_student_learning_progress_users_deleted_by;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT uq_slp_student_material TO uq_student_learning_progress_student_material;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT chk_slp_progress TO chk_student_learning_progress_progress;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT chk_slp_time_spent TO chk_student_learning_progress_time_spent;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT chk_slp_last_position TO chk_student_learning_progress_last_position;
ALTER TABLE public.student_learning_progress RENAME CONSTRAINT chk_slp_version TO chk_student_learning_progress_version;
ALTER INDEX IF EXISTS idx_slp_student RENAME TO idx_student_learning_progress_student_status;
ALTER INDEX IF EXISTS idx_slp_material RENAME TO idx_student_learning_progress_material_status;
ALTER INDEX IF EXISTS idx_slp_tenant RENAME TO idx_student_learning_progress_tenant_student_material;
ALTER INDEX IF EXISTS idx_slp_progress RENAME TO idx_student_learning_progress_tenant_progress;
ALTER INDEX IF EXISTS idx_slp_completed RENAME TO idx_student_learning_progress_tenant_completed;
-- uq_slp_tenant_id already compliant

-- 08.07 learning_bookmarks
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT learning_bookmarks_pkey TO pk_learning_bookmarks;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT fk_lb_tenant TO fk_learning_bookmarks_institutes;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT fk_lb_student TO fk_learning_bookmarks_users_student;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT fk_lb_material TO fk_learning_bookmarks_learning_materials;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT fk_lb_created_by TO fk_learning_bookmarks_users_created_by;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT fk_lb_updated_by TO fk_learning_bookmarks_users_updated_by;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT fk_lb_deleted_by TO fk_learning_bookmarks_users_deleted_by;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT chk_lb_page TO chk_learning_bookmarks_page;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT chk_lb_timestamp TO chk_learning_bookmarks_video_timestamp;
ALTER TABLE public.learning_bookmarks RENAME CONSTRAINT chk_lb_version TO chk_learning_bookmarks_version;
ALTER INDEX IF EXISTS idx_lb_student RENAME TO idx_learning_bookmarks_student_material;
ALTER INDEX IF EXISTS idx_lb_material RENAME TO idx_learning_bookmarks_material;
ALTER INDEX IF EXISTS idx_lb_tenant RENAME TO idx_learning_bookmarks_tenant_student;
-- uq_lb_tenant_id already compliant

-- 08.08 learning_notes
ALTER TABLE public.learning_notes RENAME CONSTRAINT learning_notes_pkey TO pk_learning_notes;
ALTER TABLE public.learning_notes RENAME CONSTRAINT fk_ln_tenant TO fk_learning_notes_institutes;
ALTER TABLE public.learning_notes RENAME CONSTRAINT fk_ln_student TO fk_learning_notes_users_student;
ALTER TABLE public.learning_notes RENAME CONSTRAINT fk_ln_material TO fk_learning_notes_learning_materials;
ALTER TABLE public.learning_notes RENAME CONSTRAINT fk_ln_created_by TO fk_learning_notes_users_created_by;
ALTER TABLE public.learning_notes RENAME CONSTRAINT fk_ln_updated_by TO fk_learning_notes_users_updated_by;
ALTER TABLE public.learning_notes RENAME CONSTRAINT fk_ln_deleted_by TO fk_learning_notes_users_deleted_by;
ALTER TABLE public.learning_notes RENAME CONSTRAINT chk_ln_content TO chk_learning_notes_content;
ALTER TABLE public.learning_notes RENAME CONSTRAINT chk_ln_page TO chk_learning_notes_page;
ALTER TABLE public.learning_notes RENAME CONSTRAINT chk_ln_timestamp TO chk_learning_notes_video_timestamp;
ALTER TABLE public.learning_notes RENAME CONSTRAINT chk_ln_version TO chk_learning_notes_version;
ALTER INDEX IF EXISTS idx_ln_student RENAME TO idx_learning_notes_student_material;
ALTER INDEX IF EXISTS idx_ln_material RENAME TO idx_learning_notes_material;
ALTER INDEX IF EXISTS idx_ln_tenant RENAME TO idx_learning_notes_tenant_student;
-- uq_ln_tenant_id already compliant

-- 08.09 material_discussions
ALTER TABLE public.material_discussions RENAME CONSTRAINT material_discussions_pkey TO pk_material_discussions;
ALTER TABLE public.material_discussions RENAME CONSTRAINT fk_md_tenant TO fk_material_discussions_institutes;
ALTER TABLE public.material_discussions RENAME CONSTRAINT fk_md_material TO fk_material_discussions_learning_materials;
ALTER TABLE public.material_discussions RENAME CONSTRAINT fk_md_parent TO fk_material_discussions_material_discussions;
ALTER TABLE public.material_discussions RENAME CONSTRAINT fk_md_author TO fk_material_discussions_users_author;
ALTER TABLE public.material_discussions RENAME CONSTRAINT fk_md_created_by TO fk_material_discussions_users_created_by;
ALTER TABLE public.material_discussions RENAME CONSTRAINT fk_md_updated_by TO fk_material_discussions_users_updated_by;
ALTER TABLE public.material_discussions RENAME CONSTRAINT fk_md_deleted_by TO fk_material_discussions_users_deleted_by;
ALTER TABLE public.material_discussions RENAME CONSTRAINT chk_md_comment TO chk_material_discussions_comment;
ALTER TABLE public.material_discussions RENAME CONSTRAINT chk_md_version TO chk_material_discussions_version;
ALTER INDEX IF EXISTS idx_md_material RENAME TO idx_material_discussions_material_parent;
ALTER INDEX IF EXISTS idx_md_author RENAME TO idx_material_discussions_author;
ALTER INDEX IF EXISTS idx_md_tenant RENAME TO idx_material_discussions_tenant_material;
ALTER INDEX IF EXISTS idx_md_status RENAME TO idx_material_discussions_material_status;
-- uq_md_tenant_id already compliant

-- 08.10 material_assignments
ALTER TABLE public.material_assignments RENAME CONSTRAINT material_assignments_pkey TO pk_material_assignments;
ALTER TABLE public.material_assignments RENAME CONSTRAINT fk_ma_tenant TO fk_material_assignments_institutes;
ALTER TABLE public.material_assignments RENAME CONSTRAINT fk_ma_material TO fk_material_assignments_learning_materials;
ALTER TABLE public.material_assignments RENAME CONSTRAINT fk_ma_question_bank TO fk_material_assignments_questions;
ALTER TABLE public.material_assignments RENAME CONSTRAINT fk_ma_created_by TO fk_material_assignments_users_created_by;
ALTER TABLE public.material_assignments RENAME CONSTRAINT fk_ma_updated_by TO fk_material_assignments_users_updated_by;
ALTER TABLE public.material_assignments RENAME CONSTRAINT fk_ma_deleted_by TO fk_material_assignments_users_deleted_by;
ALTER TABLE public.material_assignments RENAME CONSTRAINT uq_ma_material TO uq_material_assignments_material;
ALTER TABLE public.material_assignments RENAME CONSTRAINT chk_ma_marks TO chk_material_assignments_marks;
ALTER TABLE public.material_assignments RENAME CONSTRAINT chk_ma_submission_type TO chk_material_assignments_submission_type;
ALTER TABLE public.material_assignments RENAME CONSTRAINT chk_ma_version TO chk_material_assignments_version;
ALTER INDEX IF EXISTS idx_ma_material RENAME TO idx_material_assignments_material;
ALTER INDEX IF EXISTS idx_ma_tenant RENAME TO idx_material_assignments_tenant_material;
ALTER INDEX IF EXISTS idx_ma_due_date RENAME TO idx_material_assignments_tenant_due_date;
-- uq_ma_tenant_id already compliant

-- 08.11 assignment_submissions
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT assignment_submissions_pkey TO pk_assignment_submissions;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT fk_as_tenant TO fk_assignment_submissions_institutes;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT fk_as_assignment TO fk_assignment_submissions_material_assignments;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT fk_as_student TO fk_assignment_submissions_student_admissions;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT fk_as_evaluated_by TO fk_assignment_submissions_users_evaluated_by;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT fk_as_created_by TO fk_assignment_submissions_users_created_by;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT fk_as_updated_by TO fk_assignment_submissions_users_updated_by;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT fk_as_deleted_by TO fk_assignment_submissions_users_deleted_by;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT uq_as_attempt TO uq_assignment_submissions_attempt;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT chk_as_attempt_number TO chk_assignment_submissions_attempt_number;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT chk_as_marks TO chk_assignment_submissions_marks;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT chk_as_status TO chk_assignment_submissions_status;
ALTER TABLE public.assignment_submissions RENAME CONSTRAINT chk_as_version TO chk_assignment_submissions_version;
ALTER INDEX IF EXISTS idx_as_assignment RENAME TO idx_assignment_submissions_assignment_student;
ALTER INDEX IF EXISTS idx_as_student RENAME TO idx_assignment_submissions_student_status;
ALTER INDEX IF EXISTS idx_as_tenant RENAME TO idx_assignment_submissions_tenant_assignment;
ALTER INDEX IF EXISTS idx_as_latest RENAME TO idx_assignment_submissions_assignment_latest;
-- uq_as_tenant_id already compliant
